package ap.panini.procrastaint.data.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import ap.panini.procrastaint.data.database.dao.TaskDao
import ap.panini.procrastaint.data.model.Task

@Database(entities = [Task::class], version = 1)
@ConstructedBy(ProcrastaintDatabaseConstructor::class)
abstract class ProcrastaintDatabase : RoomDatabase() {
    abstract fun getTaskDao(): TaskDao
}

// constructor generated by compiler
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object ProcrastaintDatabaseConstructor : RoomDatabaseConstructor<ProcrastaintDatabase> {
    override fun initialize(): ProcrastaintDatabase
}
