package ap.panini.procrastaint.data.database

import androidx.room.AutoMigration
import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import ap.panini.procrastaint.data.database.dao.NetworkSyncDao
import ap.panini.procrastaint.data.database.dao.TaskDao
import ap.panini.procrastaint.data.entities.NetworkSyncItem
import ap.panini.procrastaint.data.entities.TaskCompletion
import ap.panini.procrastaint.data.entities.TaskInfo
import ap.panini.procrastaint.data.entities.TaskMeta
import ap.panini.procrastaint.data.entities.TaskTag
import ap.panini.procrastaint.data.entities.TaskTagCrossRef

@Database(
    entities = [
        TaskInfo::class,
        TaskMeta::class,
        TaskCompletion::class,
        TaskTag::class,
        TaskTagCrossRef::class,
        NetworkSyncItem::class
    ],
    version = 2,
    autoMigrations = [
        AutoMigration(from = 1, to = 2)
    ]
)
@ConstructedBy(ProcrastaintDatabaseConstructor::class)
abstract class ProcrastaintDatabase : RoomDatabase() {
    abstract fun getTaskDao(): TaskDao
    abstract fun getNetworkSyncDao(): NetworkSyncDao
}

// constructor generated by compiler
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object ProcrastaintDatabaseConstructor : RoomDatabaseConstructor<ProcrastaintDatabase> {
    override fun initialize(): ProcrastaintDatabase
}
